services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel
    expose:
      - "8080"
    volumes:
      - ./backend/database:/var/www/html/database:rw
      - ./backend/storage:/var/www/html/storage:rw
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://162.43.87.222
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - APP_KEY=base64:VhQa+IQ13kR/0dV3u+XmPkvRMuuGyTTSUZh0Hy01SWg=
      - SANCTUM_STATEFUL_DOMAINS=162.43.87.222
      - SESSION_DOMAIN=162.43.87.222
    command: php artisan serve --host=0.0.0.0 --port=8080
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8090:80"
    volumes:
      - ./nginx-production.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - laravel
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
