services:
  # Laravel Backend with PHP-FPM
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: feed-laravel-dev
    ports:
      - "8081:8080"
    volumes:
      - ./backend:/var/www/html
      - ./backend/database:/var/www/html/database
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - APP_KEY=${APP_KEY:-base64:VhQa+IQ13kR/0dV3u+XmPkvRMuuGyTTSUZh0Hy01SWg=}
      - APP_URL=http://localhost:8080
      - SANCTUM_STATEFUL_DOMAINS=localhost:3000,localhost:8080
      - SESSION_DOMAIN=localhost
    command: php artisan serve --host=0.0.0.0 --port=8080
    restart: unless-stopped
    networks:
      - feed-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/categories || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Next.js Frontend
  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: feed-nextjs-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api
      - PORT=3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    networks:
      - feed-network
    depends_on:
      laravel:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  feed-network:
    driver: bridge