services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: feed-mysql
    env_file:
      - .env.docker
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    restart: unless-stopped
    networks:
      - feed-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Laravel Backend with PHP-FPM
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: feed-laravel
    ports:
      - "127.0.0.1:9000:9000"  # セキュリティ: localhost のみバインド
    volumes:
      - storage_data:/var/www/html/storage:rw
      - laravel_logs:/var/www/html/storage/logs:rw
    env_file:
      - .env.docker
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - CACHE_CLEAR_FORCE=true
    restart: unless-stopped
    networks:
      - feed-network
    depends_on:
      mysql:
        condition: service_healthy
    # セキュリティ制約
    security_opt:
      - no-new-privileges:true
    read_only: false  # Laravel needs write access to cache/logs
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    healthcheck:
      test: ["CMD-SHELL", "php-fpm -t"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Next.js Frontend
  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: feed-nextjs
    env_file:
      - .env.docker
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    networks:
      - feed-network
    # セキュリティ制約
    security_opt:
      - no-new-privileges:true
    # Next.js は画像最適化キャッシュのため /app/.next/cache に書き込み必要
    read_only: false
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    # depends_on:
    #   laravel:
    #     condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: feed-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - nginx_logs:/var/log/nginx:rw
      - storage_data:/var/www/html/storage:ro
      - ./frontend/public/favicon.ico:/var/www/favicon.ico:ro
    # セキュリティ制約
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /var/cache/nginx:noexec,nosuid,size=50m
      - /var/run:noexec,nosuid,size=10m
      - /tmp:noexec,nosuid,size=10m
    # depends_on:
    #   laravel:
    #     condition: service_healthy
    #   nextjs:
    #     condition: service_started
    restart: unless-stopped
    networks:
      - feed-network
    healthcheck:
      test: ["CMD-SHELL", "nginx -t"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  mysql_data:
    driver: local
  storage_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./backend/storage
  laravel_logs:
    driver: local
  nginx_logs:
    driver: local

networks:
  feed-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16