version: '3.8'

services:
  # Laravel Backend with PHP-FPM
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: feed-laravel
    volumes:
      - ./backend:/var/www/html
      - sqlite_data:/var/www/html/database
      - storage_data:/var/www/html/storage
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - APP_KEY=${APP_KEY:-base64:dGVzdF9rZXlfZm9yX2RlbW9fcHVycG9zZXNfb25seQ==}
    ports:
      - "9000:9000"
    restart: unless-stopped
    networks:
      - feed-network
    healthcheck:
      test: ["CMD-SHELL", "php-fpm -t"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Next.js Frontend
  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: feed-nextjs
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://laravel:9000/api
      - PORT=3000
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - feed-network
    depends_on:
      laravel:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: feed-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/public:/var/www/html/public:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      laravel:
        condition: service_healthy
      nextjs:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - feed-network
    healthcheck:
      test: ["CMD-SHELL", "nginx -t"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  sqlite_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./backend/database
  storage_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./backend/storage
  nginx_logs:
    driver: local

networks:
  feed-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16