services:
  nginx:
    image: nginx:alpine
    container_name: feed-nginx-simple
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./backend/public:/var/www/html/public:ro
      - ./frontend/out:/var/www/html/frontend:ro
    restart: unless-stopped
    networks:
      - feed-network

  php:
    image: php:8.2-fpm-alpine
    container_name: feed-php-simple
    volumes:
      - ./backend:/var/www/html:rw
    working_dir: /var/www/html
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    restart: unless-stopped
    networks:
      - feed-network

networks:
  feed-network:
    driver: bridge
EOF < /dev/null
