services:
  # Laravel Backend with PHP-FPM
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: feed-laravel-prod
    volumes:
      - sqlite_data:/var/www/html/database
      - storage_data:/var/www/html/storage
      - laravel_logs:/var/www/html/storage/logs
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - APP_KEY=base64:VhQa+IQ13kR/0dV3u+XmPkvRMuuGyTTSUZh0Hy01SWg=
      - APP_URL=https://designcreateform.com
      - SANCTUM_STATEFUL_DOMAINS=designcreateform.com,www.designcreateform.com
      - SESSION_DOMAIN=.designcreateform.com
    restart: unless-stopped
    networks:
      - feed-network
    healthcheck:
      test: ["CMD-SHELL", "php-fpm -t"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Next.js Frontend
  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: feed-nextjs-prod
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://designcreateform.com/api
      - PORT=3000
    restart: unless-stopped
    networks:
      - feed-network
    depends_on:
      laravel:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: feed-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      laravel:
        condition: service_healthy
      nextjs:
        condition: service_started
    restart: unless-stopped
    networks:
      - feed-network
    healthcheck:
      test: ["CMD-SHELL", "nginx -t"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  sqlite_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./backend/database
  storage_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./backend/storage
  laravel_logs:
    driver: local
  nginx_logs:
    driver: local

networks:
  feed-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16