services:
  nginx:
    image: nginx:alpine
    container_name: feed-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx-simple.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

  laravel:
    image: php:8.2-fpm
    container_name: feed-laravel
    working_dir: /var/www/html
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/var/www/html
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://162.43.87.222
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - APP_KEY=base64:VhQa+IQ13kR/0dV3u+XmPkvRMuuGyTTSUZh0Hy01SWg=
    restart: unless-stopped