services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: feed-laravel-final
    ports:
      - "8080:8080"
    volumes:
      - ./backend/database:/var/www/html/database:rw
      - ./backend/storage:/var/www/html/storage:rw
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://162.43.87.222:8080
      - SANCTUM_STATEFUL_DOMAINS=162.43.87.222
      - SESSION_DOMAIN=162.43.87.222
    command: php artisan serve --host=0.0.0.0 --port=8080
    restart: unless-stopped

  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: feed-nextjs-final
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://162.43.87.222:8080/api
    restart: unless-stopped
    depends_on:
      - laravel
EOF < /dev/null
